// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmSrlZkWOxBHnDZgRY7czF-xA0USGGpP8',
    appId: '1:379037893915:web:1198df18c6ea8a41bc3fbe',
    messagingSenderId: '379037893915',
    projectId: 'app-salon-c03fc',
    authDomain: 'app-salon-c03fc.firebaseapp.com',
    storageBucket: 'app-salon-c03fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI4RKWWTjCc_AJGnZM_0RRwJLiKN7ITHY',
    appId: '1:379037893915:android:34b656fb249b38d9bc3fbe',
    messagingSenderId: '379037893915',
    projectId: 'app-salon-c03fc',
    storageBucket: 'app-salon-c03fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9WwemH4HE6yAFBPkVVs0_JLN35ldOMk0',
    appId: '1:379037893915:ios:6d101c22226c59f5bc3fbe',
    messagingSenderId: '379037893915',
    projectId: 'app-salon-c03fc',
    storageBucket: 'app-salon-c03fc.appspot.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9WwemH4HE6yAFBPkVVs0_JLN35ldOMk0',
    appId: '1:379037893915:ios:6d101c22226c59f5bc3fbe',
    messagingSenderId: '379037893915',
    projectId: 'app-salon-c03fc',
    storageBucket: 'app-salon-c03fc.appspot.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmSrlZkWOxBHnDZgRY7czF-xA0USGGpP8',
    appId: '1:379037893915:web:2c7b6bb5a3c0fd65bc3fbe',
    messagingSenderId: '379037893915',
    projectId: 'app-salon-c03fc',
    authDomain: 'app-salon-c03fc.firebaseapp.com',
    storageBucket: 'app-salon-c03fc.appspot.com',
  );
}
